# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muss < Formula
  desc ""
  homepage ""
  version "0.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/muss/releases/download/v0.10/muss_0.10_Darwin_arm64.tar.gz"
      sha256 "6e388d112089208350ba681f08612af1e2beb2d54d915f878338a291cab747f5"

      def install
        bin.install "muss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/muss/releases/download/v0.10/muss_0.10_Darwin_x86_64.tar.gz"
      sha256 "f0d45c312464a531542f28bae8ffe36e9331b85eade42f9fe915abc0126127e6"

      def install
        bin.install "muss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/muss/releases/download/v0.10/muss_0.10_Linux_arm64.tar.gz"
      sha256 "e829fcd1884ae0f68e1f0b839e951e90f360013db5fd3d03f8c5c97ca2bdda7d"

      def install
        bin.install "muss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/muss/releases/download/v0.10/muss_0.10_Linux_x86_64.tar.gz"
      sha256 "11fc7f3061aa177cfefa88043597d220bf83e51f991bc513d65c3176818303ef"

      def install
        bin.install "muss"
      end
    end
  end

  depends_on "vault"

  test do
    system bin/"muss", "help"
  end
end
